In [ ]:
import pandas as pd
from pathlib import Path

In [4]:
DATA_DIR = Path("../data")

In [ ]:
product_df = pd.read_csv(
    DATA_DIR / "PublicTablesForCarbonCatalogueDataDescriptor_v30Oct2021(Product Level Data).csv",
    encoding="latin1"
)

stage_df = pd.read_csv(
    DATA_DIR / "PublicTablesForCarbonCatalogueDataDescriptor_v30Oct2021(Stage Level Data).csv",
    encoding="latin1"
)

glossary_df = pd.read_csv(
    DATA_DIR / "PublicTablesForCarbonCatalogueDataDescriptor_v30Oct2021(Glossary).csv",
    encoding="latin1"
)

# UnicodeDecodeError means your CSV file is not encoded in UTF-8, while pandas.read_csv() assumes UTF-8 by default.

# Solution 1 (Most Common) – Try latin1

In [7]:
glossary_df.head(10)

,Fieldname,Table,Source,Type,Short explanation (see manuscript for further detail)
0,PCF-ID,Product & stage level,Added during study,Text,"Concatenation of custom company ID, product, a..."
1,Year of reporting,Product level,Raw data as reported to CDP,Numeric,N/a
2,Stage-level CO2e available,Product level,Added during study,Text,"""Yes"" indicates that product will appear in st..."
3,Product name (and functional unit),Product level,Raw data as reported to CDP,Text,Name or short product description as provided ...
4,Product detail,Product level,Raw data as reported to CDP,Text,Detailed product description as provided by re...
5,Company,Product level,Raw data as reported to CDP,Text,N/a
6,Country (where company is incorporated),Product level,Raw data as reported to CDP,Text,Note this may differ from the country where th...
7,Company's GICS Industry Group,Product level,Raw data as reported to CDP,Text,GICS = Global Industry Classification Standard...
8,Company's GICS Industry,Product level,Raw data as reported to CDP,Text,GICS = Global Industry Classification Standard...
9,Company's sector,Product level,Added during study,Text,"1 of 8 broader industry sectors, defined and m..."

In [9]:
print("Product Dataset:", product_df.shape)
print("Stage Dataset:", stage_df.shape)
print("Glossary:", glossary_df.shape)

Product Dataset: (866, 25)
Stage Dataset: (1764, 7)
Glossary: (31, 5)

In [10]:
product_df.head()

,*PCF-ID,Year of reporting,*Stage-level CO2e available,Product name (and functional unit),Product detail,Company,Country (where company is incorporated),Company's GICS Industry Group,Company's GICS Industry,*Company's sector,...,Relative change in PCF vs previous,Company-reported reason for change,*Change reason category,*%Upstream estimated from %Operations,*Upstream CO2e (fraction of total PCF),*Operations CO2e (fraction of total PCF),*Downstream CO2e (fraction of total PCF),*Transport CO2e (fraction of total PCF),*EndOfLife CO2e (fraction of total PCF),*Adjustments to raw data (if any)
0,10056-1-2014,2014,Yes,Frosted Flakes(R) Cereal,"Frosted Flakes(R), 23 oz., Produced in Lancast...",Kellogg Company,USA,"Food, Beverage & Tobacco",Food Products,Food & Beverage,...,(not reported by company),N/a,N/a (no %change reported),No,57.50%,30.00%,12.50%,4.50%,(included in downstream but not reported separ...,Divided stage and total emissions by 1000 (bas...
1,10056-1-2015,2015,Yes,"Frosted Flakes, 23 oz, produced in Lancaster, ...",Cereal,Kellogg Company,USA,Food & Beverage Processing,Not used for 2015 reporting,Food & Beverage,...,(not reported by company),N/a,N/a (no %change reported),No,57.50%,30.00%,12.50%,4.50%,(included in downstream but not reported separ...,Divided stage and total emissions by 1000 (bas...
2,10222-1-2013,2013,Yes,Office Chair,Field not included in 2013 data,KNOLL INC,USA,Capital Goods,Building Products,Comm. equipm. & capital goods,...,(not reported by company),N/a,N/a (no previous data available),Yes,80.63%,17.36%,2.01%,(included in up/downstream but not reported se...,0.00%,"Changed %change to zero, according to field ""c..."
3,10261-1-2017,2017,Yes,Multifunction Printers,bizhub C458,"Konica Minolta, Inc.",Japan,Technology Hardware & Equipment,"Electronic Equipment, Instruments & Components","Computer, IT & telecom",...,(not reported by company),N/a,N/a (no previous data available),No,30.65%,5.51%,63.84%,1.01%,2.76%,NaN
4,10261-2-2017,2017,Yes,Multifunction Printers,bizhub C558,"Konica Minolta, Inc.",Japan,Technology Hardware & Equipment,"Electronic Equipment, Instruments & Components","Computer, IT & telecom",...,(not reported by company),N/a,N/a (no previous data available),No,25.08%,4.51%,70.41%,0.83%,2.26%,NaN

In [11]:
product_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 866 entries, 0 to 865
Data columns (total 25 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   *PCF-ID                                    866 non-null    str
 1   Year of reporting                          866 non-null    int64
 2   *Stage-level CO2e available                866 non-null    str
 3   Product name (and functional unit)         866 non-null    str
 4   Product detail                             856 non-null    str
 5   Company                                    866 non-null    str
 6   Country (where company is incorporated)    866 non-null    str
 7   Company's GICS Industry Group              866 non-null    str
 8   Company's GICS Industry                    866 non-null    str
 9   *Company's sector                          866 non-null    str
 10  Product weight (kg)                        866 non-null    float64
 11  *Source for product weight                 866 non-null    str
 12  Product's carbon footprint (PCF, kg CO2e)  866 non-null    float64
 13  *Carbon intensity                          866 non-null    float64
 14  Protocol used for PCF                      866 non-null    str
 15  Relative change in PCF vs previous         866 non-null    str
 16  Company-reported reason for change         866 non-null    str
 17  *Change reason category                    866 non-null    str
 18  *%Upstream estimated from %Operations      866 non-null    str
 19  *Upstream CO2e (fraction of total PCF)     866 non-null    str
 20  *Operations CO2e (fraction of total PCF)   866 non-null    str
 21  *Downstream CO2e (fraction of total PCF)   866 non-null    str
 22  *Transport CO2e (fraction of total PCF)    866 non-null    str
 23  *EndOfLife CO2e (fraction of total PCF)    866 non-null    str
 24  *Adjustments to raw data (if any)          187 non-null    str
dtypes: float64(3), int64(1), str(21)
memory usage: 169.3 KB

In [12]:
product_df.isnull().sum()

*PCF-ID                                        0
Year of reporting                              0
*Stage-level CO2e available                    0
Product name (and functional unit)             0
Product detail                                10
Company                                        0
Country (where company is incorporated)        0
Company's GICS Industry Group                  0
Company's GICS Industry                        0
*Company's sector                              0
Product weight (kg)                            0
*Source for product weight                     0
Product's carbon footprint (PCF, kg CO2e)      0
*Carbon intensity                              0
Protocol used for PCF                          0
Relative change in PCF vs previous             0
Company-reported reason for change             0
*Change reason category                        0
*%Upstream estimated from %Operations          0
*Upstream CO2e (fraction of total PCF)         0
*Operations CO2e (fraction of total PCF)       0
*Downstream CO2e (fraction of total PCF)       0
*Transport CO2e (fraction of total PCF)        0
*EndOfLife CO2e (fraction of total PCF)        0
*Adjustments to raw data (if any)            679
dtype: int64

In [13]:
product_df.duplicated().sum()

np.int64(0)

In [ ]:
stage_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1764 entries, 0 to 1763
Data columns (total 7 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   *PCF-ID                                             1764 non-null   str
 1   Description of LCA stage                            1764 non-null   str
 2   Scope-characterization of LCA stage                 1764 non-null   str
 3   *Assigned value chain portion                       1764 non-null   str
 4   Emissions at stage (kg CO2e)                        1764 non-null   float64
 5   *Emissions at this stage are exclusively transport  1764 non-null   str
 6   *Emissions at this stage are exclusively EndOfLife  1764 non-null   str
dtypes: float64(1), str(6)
memory usage: 96.6 KB

In [17]:
glossary_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 5 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   Fieldname                                              31 non-null     str
 1   Table                                                  31 non-null     str
 2   Source                                                 31 non-null     str
 3   Type                                                   31 non-null     str
 4   Short explanation (see manuscript for further detail)  31 non-null     str
dtypes: str(5)
memory usage: 1.3 KB

In [19]:
product_df.describe(include='all')

,*PCF-ID,Year of reporting,*Stage-level CO2e available,Product name (and functional unit),Product detail,Company,Country (where company is incorporated),Company's GICS Industry Group,Company's GICS Industry,*Company's sector,...,Relative change in PCF vs previous,Company-reported reason for change,*Change reason category,*%Upstream estimated from %Operations,*Upstream CO2e (fraction of total PCF),*Operations CO2e (fraction of total PCF),*Downstream CO2e (fraction of total PCF),*Transport CO2e (fraction of total PCF),*EndOfLife CO2e (fraction of total PCF),*Adjustments to raw data (if any)
count,866,866.000000,866,866,856,866,866,866,866,866,...,866,866,866,866,866,866,866,866,866,187
unique,866,NaN,2,672,496,145,28,30,35,8,...,145,157,6,3,338,317,276,208,122,58
top,10056-1-2014,NaN,No,Tetra Brik® Aseptic Slim 200ml,Field not included in 2013 data,Daimler AG,USA,Technology Hardware & Equipment,Not used for 2015 reporting,"Computer, IT & telecom",...,(not reported by company),N/a,N/a (no %change reported),N/a (product with insufficient stage-level data),N/a (product with insufficient stage-level data),N/a (product with insufficient stage-level data),N/a (product with insufficient stage-level data),N/a (product with insufficient stage-level data),N/a (product with insufficient stage-level data),Concatenated fields product name and product d...
freq,1,NaN,445,4,97,37,305,195,215,253,...,616,654,482,445,445,445,445,445,445,29
mean,NaN,2014.762125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,1.236720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,2013.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,2014.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,2015.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,2016.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,2017.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
stage_df.describe(include='all')

,*PCF-ID,Description of LCA stage,Scope-characterization of LCA stage,*Assigned value chain portion,Emissions at stage (kg CO2e),*Emissions at this stage are exclusively transport,*Emissions at this stage are exclusively EndOfLife
count,1764,1764,1764,1764,1764.000000,1764,1764
unique,421,254,8,3,NaN,2,2
top,12942-1-2013,Transportation,Scope 3,Downstream,NaN,No,No
freq,9,160,662,792,NaN,1447,1564
mean,NaN,NaN,NaN,NaN,705.020937,NaN,NaN
std,NaN,NaN,NaN,NaN,5960.331979,NaN,NaN
min,NaN,NaN,NaN,NaN,-502.800000,NaN,NaN
25%,NaN,NaN,NaN,NaN,0.163775,NaN,NaN
50%,NaN,NaN,NaN,NaN,6.036500,NaN,NaN
75%,NaN,NaN,NaN,NaN,104.550000,NaN,NaN
max,NaN,NaN,NaN,NaN,185315.000000,NaN,NaN

In [22]:
glossary_df.describe(include='all')

,Fieldname,Table,Source,Type,Short explanation (see manuscript for further detail)
count,31,31,31,31,31
unique,31,3,2,3,25
top,PCF-ID,Product level,Added during study,Text,N/a
freq,1,24,16,20,6